name: MasterDeploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: csye6225-webapp-${{ github.run_number }}.zip
      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Unit Test
        run: |
          npm i && npm test

      - name: Build Zip File
        run: |
          mkdir codedeploy_artifact
          zip -r nodeApi . -x ".git/*" ".github/*" "node_modules/*" "package-lock.json"
          mv nodeApi.zip codedeploy_artifact

      - name: Run Packer Container - Validate Template
        run: |
          cd packer
          packer init nodeApi.pkr.hcl
          packer validate \
           -var 'aws_access_key=$AWS_ACCESS_KEY' \
           -var 'aws_secret_key=$AWS_SECRET_KEY' \
           -var-file=var.json nodeApi.pkr.hcl

  # validate:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: Run Packer Container - Validate Template
  #     - uses: docker://hashicorp/packer:light
  #       # with:
  #       #   path: "./packer"
  #       run: |
  #         pwd
  #         ls

  # packer_build:
  #   runs-on: ubuntu-latest
  #   env:
  #     ARTIFACT_NAME: Network-Structure-Cloud-Computing-webservice-${{ github.run_number }}.zip
  #   needs: packer_validate
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}

  #   - name: Packer build
  #     uses: ExitoLab/packer_build_action_aws@v0.2.10
  #     with:
  #       templateFile: 'nodeApi.pkr.hcl'
  #       workingDir: '/home/runner/work/webservice/webservice/packer'
  #       varFile: 'var.json'
  #     env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       AWS_REGION: us-east-1
  # - name: Validate Packer
  #   run: |
  #     cd packer
  #     echo ${{ env.AWS_ACCESS_KEY }}
  #     packer init nodeApi.pkr.hcl
  #     packer build \
  #      -var 'aws_access_key=$AWS_ACCESS_KEY' \
  #      -var 'aws_secret_key=$AWS_SECRET_KEY' \
  #      -var-file=var.json nodeApi.pkr.hcl

  # - name: Run Packer
  #   run: |
  #      cd packer
  #      packer build \
  #      -var 'aws_access_key=$AWS_ACCESS_KEY' \
  #      -var 'aws_secret_key=$AWS_SECRET_KEY' \
  #      -var-file=var.json nodeApi.pkr.hcl
