name: MasterDeploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: Network-Structure-Cloud-Computing-webservice-${{ github.run_number }}.zip
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Unit Test
      run: |
        npm i && npm test
    
    - name: Build Zip File
      run: | 
        mkdir codedeploy_artifact
        zip -r nodeApi . -x ".git/*" ".github/*" "node_modules/*" "package-lock.json"
        mv nodeApi.zip codedeploy_artifact
        pwd
        cd codedeploy_artifact
        pwd
        ls
