name: MasterDeploy

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: Network-Structure-Cloud-Computing-webservice-${{ github.run_number }}.zip
      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      SUBNET_ID: ${{secrets.SUBNET_ID}}
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Unit Test
      run: |
        npm i && npm test
    
    - name: Build Zip File
      run: | 
        mkdir codedeploy_artifact
        zip -r nodeApi . -x ".git/*" ".github/*" "node_modules/*" "package-lock.json"
        mv nodeApi.zip codedeploy_artifact
        cd codedeploy_artifact
    
    - name: Validate Packer
      run: |
        cd packer
        echo ${{ AWS_REGION }}
        packer init nodeApi.pkr.hcl
        packer build \
         -var 'aws_access_key=$AWS_ACCESS_KEY' \
         -var 'aws_secret_key=$AWS_SECRET_KEY' \
         -var 'aws_region=$AWS_REGION' \
         -var 'subnet_id=$SUBNET_ID' \
         -var-file=var.json nodeApi.pkr.hcl

    - name: Run Packer
      run: |
         cd packer
         packer build \
         -var 'aws_access_key=$AWS_ACCESS_KEY' \
         -var 'aws_secret_key=$AWS_SECRET_KEY' \
         -var 'aws_region=$AWS_REGION' \
         -var 'subnet_id=$SUBNET_ID' \
         -var-file=var.json nodeApi.pkr.hcl