name: Master Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: csye6225-webapp-${{ github.run_number }}.zip
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Unit Test
        run: |
          npm i && npm test

      - name: Build Zip File
        run: |
          mkdir codedeploy_artifact
          zip -r nodeApi . -x ".git/*" ".github/*" "node_modules/*" "package-lock.json" "packer/*"
          mv nodeApi.zip codedeploy_artifact

      - name: Run Packer Container - Validate Template
        run: |
          cd packer
          packer init nodeApi.pkr.hcl
          packer validate -var-file=var.json nodeApi.pkr.hcl

      - name: Run Packer Container - Building Packer Template
        env:
          AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          SUBNET_ID: ${{secrets.SUBNET_ID}}
          AWS_DEMO_ACCOUNT_ID: ${{secrets.AWS_DEMO_ACCOUNT_ID}}
          ZIP_FILE_PATH: ${{secrets.ZIP_FILE_PATH}}
        run: |
          cd packer
          packer build -var-file=var.json nodeApi.pkr.hcl
