name: MasterDeploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: Network-Structure-Cloud-Computing-webservice-${{ github.run_number }}.zip
      aws_access_key: secrets.AWS_ACCESS_KEY
      aws_secret_key: secrets.AWS_SECRET_KEY
      aws_region: secrets.AWS_REGION
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Unit Test
      run: |
        npm i && npm test
    
    - name: Build Zip File
      run: | 
        mkdir codedeploy_artifact
        zip -r nodeApi . -x ".git/*" ".github/*" "node_modules/*" "package-lock.json"
        mv nodeApi.zip codedeploy_artifact
        cd codedeploy_artifact
    
    - name: Validate Packer
      run: |
        cd packer
        packer init
        packer validate -var-file=var.json nodeApi.pkr.hcl

    - name: Run Packer
      run: |
        ls