# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Validate Packer

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Validate Packer
    runs-on: ubuntu-latest
    env:
      aws_access_key: secrets.AWS_ACCESS_KEY
      aws_secret_key: secrets.AWS_SECRET_KEY
      aws_region: secrets.AWS_REGION
      subnet_id: secrets.SUBNET_ID
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2
       with:
        node-version: ${{ matrix.node-version }}
     - name: Validate Packer
       run: |
        cd packer
        packer init nodeApi.pkr.hcl
        packer validate -var-file=var.json nodeApi.pkr.hcl